name: Build and Deploy Docker WebApp

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted        # IMPORTANT: runs on your local Ubuntu VM
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t webapp:latest .

      - name: Stop old container if exists
        run: |
          docker stop webapp || true
          docker rm webapp || true

      - name: Run new container
        run: docker run -d -p 8080:8080 --name webapp webapp:latest
